name: budjar
description: "Vault Path - Modern Expense Tracker - Track your expenses and savings with beautiful charts and analytics."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # For web, we'll use in-memory storage for now
  universal_html: ^2.2.4

  # State Management
  provider: ^6.1.2

  # Charts and Graphs
  fl_chart: ^0.69.0

  # Calendar
  table_calendar: ^3.0.9

  # Navigation
  go_router: ^14.3.0

  # Local Storage
  shared_preferences: ^2.5.3

  # UI Components
  google_fonts: ^4.0.4
  flutter_slidable: ^3.0.1

  # Date and Time
  intl: ^0.19.0

  # Icons
  flutter_iconpicker: ^3.2.4

  # Utils
  uuid: ^4.5.1

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.12.0

  # Ads
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4




  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/vault_path_icon.png"
  adaptive_icon_foreground: "assets/vault_path_icon_2.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  min_sdk_android: 21
  